
export const Events = {
  PARTIAL_UPDATE: "PARTIAL_UPDATE",
  FULL_UPDATE: "FULL_UPATED",
  ERROR: "ERROR",
  JOIN_GAME: "JOIN_GAME",

  MOVE_CARD_FROM_DESK_TO_HAND: "MOVE_CARD_FROM_DESK_TO_HAND",
  MOVE_CARD_FROM_HAND_TO_DESK: "MOVE_CARD_FROM_HAND_TO_DESK",
  MOVE_CARD_FROM_DESK_TO_DESK: "MOVE_CARD_FROM_DESK_TO_DESK",
  MOVE_CARD_FROM_HAND_TO_HAND: "MOVE_CARD_FROM_HAND_TO_HAND",
}