
export const Events = {

  // Server events
  PARTIAL_UPDATE: "PARTIAL_UPDATE",
  FULL_UPDATE: "FULL_UPATED",
  GAME_IS_FOUND: "GAME_IS_FOUND",
  ERROR: "ERROR",

  // Client events
  JOIN_GAME: "JOIN_GAME",
  FIND_GAME: "FIND_GAME",
  MOVE_CARD_FROM_DESK_TO_HAND: "MOVE_CARD_FROM_DESK_TO_HAND",
  MOVE_CARD_FROM_HAND_TO_DESK: "MOVE_CARD_FROM_HAND_TO_DESK",
  MOVE_CARD_FROM_DESK_TO_DESK: "MOVE_CARD_FROM_DESK_TO_DESK",
  MOVE_CARD_FROM_HAND_TO_HAND: "MOVE_CARD_FROM_HAND_TO_HAND",
  COMPLETE_TURN: "COMPLETE_TURN",

}